<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>

    <PackageId>ForgePoint.Identity.Storage</PackageId>
    <Description>Storage interfaces and models for ForgePoint.Identity</Description>
    <AssemblyName>ForgePoint.Identity.Storage</AssemblyName>

    <PackageTags>OAuth2;OAuth 2.0;OpenID Connect;Security;Identity;ForgePoint;IdentityServer4</PackageTags>
    <PackageIcon>icon.jpg</PackageIcon>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>

    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>

    <AssemblyOriginatorKeyFile>../../../key.snk</AssemblyOriginatorKeyFile>
    <SignAssembly>true</SignAssembly>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <ContinuousIntegrationBuild Condition="'$(TF_BUILD)' == 'true'">True</ContinuousIntegrationBuild>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">True</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../../icon.jpg" Pack="true" Visible="false" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IdentityModel" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
  </ItemGroup>

</Project>