<Project>

  <PropertyGroup>
    <MinVerMinimumMajorMinor>10.0</MinVerMinimumMajorMinor>
    <MinVerTagPrefix></MinVerTagPrefix>

    <IdentityServerVersion>10.0.0-*</IdentityServerVersion>

    <AspNetCoreVersion Condition="'$(TargetFramework)' == 'net8.0'">8.0.21</AspNetCoreVersion>
    <AspNetCoreVersion Condition="'$(TargetFramework)' == 'net10.0'">10.0.11</AspNetCoreVersion>
    <AspNetCoreVersion Condition="'$(AspNetCoreVersion)' == ''">10.0.11</AspNetCoreVersion>

    <EntityFrameworkVersion Condition="'$(TargetFramework)' == 'net8.0'">8.0.21</EntityFrameworkVersion>
    <EntityFrameworkVersion Condition="'$(TargetFramework)' == 'net10.0'">10.0.11</EntityFrameworkVersion>
    <EntityFrameworkVersion Condition="'$(EntityFrameworkVersion)' == ''">10.0.11</EntityFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <!--build related-->
    <PackageReference Include="MinVer" Version="6.0.0" PrivateAssets="All" />
    <PackageReference Update="SimpleExec" Version="6.2.0" />
    <PackageReference Update="Bullseye" Version="3.3.0" />
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />

    <!--tests -->
    <PackageReference Update="FluentAssertions" Version="5.10.3" />
    <PackageReference Update="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Update="xunit" Version="2.9.3" />
    <PackageReference Update="xunit.runner.visualstudio" Version="2.8.2" PrivateAssets="All" />

    <!--our stuff -->
    <PackageReference Update="IdentityModel" Version="6.2.0" />

    <PackageReference Update="IdentityServer4" Version="$(IdentityServerVersion)" />
    <PackageReference Update="IdentityServer4.AspNetIdentity" Version="$(IdentityServerVersion)" />
    <PackageReference Update="IdentityServer4.Storage" Version="$(IdentityServerVersion)" />
    <PackageReference Update="IdentityServer4.EntityFramework.Storage" Version="$(IdentityServerVersion)" />
    <PackageReference Update="IdentityServer4.EntityFramework" Version="$(IdentityServerVersion)" />

    <!--microsoft extensions -->
    <PackageReference Update="Microsoft.Extensions.Caching.Memory" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.Extensions.Http" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.Extensions.Http.Polly" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.Extensions.Logging" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.Extensions.Logging.Console" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.Extensions.Options.ConfigurationExtensions" Version="$(AspNetCoreVersion)" />
    
    <!--misc -->
    <PackageReference Update="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Update="Microsoft.IdentityModel.Protocols.OpenIdConnect" Version="8.19.2" />
    <PackageReference Update="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
    <PackageReference Update="System.Security.Principal.Windows" Version="5.0.0" />
    <PackageReference Update="AutoMapper" Version="13.0.1" />
    
    <!--microsoft asp.net core -->
    <PackageReference Update="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.TestHost" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Identity" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="$(AspNetCoreVersion)" />
    <PackageReference Update="Microsoft.AspNetCore.Authentication.Certificate" Version="$(AspNetCoreVersion)"/>
    
    <!--microsoft entity framework -->
    <PackageReference Update="Microsoft.EntityFrameworkCore.Relational" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Sqlite" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.InMemory" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.SqlServer" Version="$(EntityFrameworkVersion)" />
    <PackageReference Update="Microsoft.EntityFrameworkCore.Design" Version="$(EntityFrameworkVersion)" PrivateAssets="All" />

  </ItemGroup>

  <Target Name="SetAssemblyVersion" AfterTargets="MinVer">
    <PropertyGroup>
      <AssemblyVersion>$(MinVerMajor).$(MinVerMinor).$(MinVerPatch).0</AssemblyVersion>
    </PropertyGroup>
  </Target>
</Project>
